In [1]:
%pip install "torch==2.2.2" tensorboard
%pip install --upgrade "transformers==4.40.0" "datasets==2.18.0" "accelerate==0.29.3" "evaluate==0.4.1" "bitsandbytes==0.43.1" "huggingface_hub==0.22.2" "trl==0.8.6" "peft==0.10.0"


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 755.5/755.5 MB 2.2 MB/s eta 0:00:000:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 410.6/410.6 MB 2.1 MB/s eta 0:00:00:00:01m00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.1/14.1 MB 101.4 MB/s eta 0:00:0000:010:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.7/23.7 MB 85.5 MB/s eta 0:00:00:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 823.6/823.6 kB 46.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 731.7/731.7 MB 2.2 MB/s eta 0:00:000:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.6/121.6 MB 2.1 MB/s eta 0:00:000:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.5/56.5 MB 31.2 MB/s eta 0:00:00:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.2/124.2 MB 14.0 MB/s eta 0:00:00:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 196.0/196.0 MB 8.8 MB/s eta 0:00:000:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 166.0/166.0 MB 10.4 MB/s eta 0:00:00:00:0100:01
   ━━━

In [2]:
from huggingface_hub import login

login(token="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")

Token has not been saved to git credential helper. Pass `add_to_git_credential=True` if you want to set the git credential as well.
Token is valid (permission: read).
Your token has been saved to /root/.cache/huggingface/token
Login successful


In [3]:
import os
import torch
import torch.nn.functional as F
import evaluate
import numpy as np
import pandas as pd
from datasets import Dataset, DatasetDict
from transformers import (
    AutoModelForSequenceClassification,
    AutoTokenizer,
    BitsAndBytesConfig,
    TrainingArguments,
    Trainer,
    DataCollatorWithPadding
)
from peft import LoraConfig, prepare_model_for_kbit_training, get_peft_model
from sklearn.metrics import balanced_accuracy_score, accuracy_score, confusion_matrix, classification_report

In [207]:
!pip install evaluate

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)


In [208]:
!pip install bitsandbytes accelerate


huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)


In [209]:
!pip install peft


huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)


In [159]:
df = pd.read_excel("/kaggle/input/dataaaa/reshaped_output2 (6).xlsx")
# Slice the first 1951 rows
df = df.iloc[:1592]

# Display the DataFrame or its information
df


Image type                                               Post Severity  \
0       Unknown  السلام عليكم انا بنت 19 سنة  , و رجلي اليمين ب...      حرج   
1       Unknown          يخوان شو الحل مع القولون العصبي مشان الله  غير حرج   
2       Unknown  لو سمحتوا أنا اتخبط في وشي خبطة جامدة وبقالي ث...      حرج   
3       Unknown  حاله اجهاد دائمه وصداع متقطع من وقت للتانى تغي...  غير حرج   
4       Unknown  عندي 21 سنه تركيزي منعدم بنسى بسرعه ومبركزش \n...  غير حرج   
...         ...                                                ...      ...   
1587        NaN                    شعرى وقع من الامام فقط اعمل ايه  غير حرج   
1588        NaN  لو سمحت يادكتور هل يوجد كريم خافي للعيوب كونسي...  غير حرج   
1589        NaN  عندي تساقط الشعر بدرجة كبيرة لدرجة احط يدي على...      حرج   
1590        NaN  بشرتي دهنيه حساسه ودايما بتأكسد حتى وانا ف الب...  غير حرج   
1591        NaN                              علاج للاكزيما العصبية      حرج   

                  Diagnosis             Type  \
0                 مخ واعصاب        مخ واعصاب   
1                قولون عصبي            باطنه   
2             كدمه في الوجه  انف واذن وحنجره   
3                       ضغط            باطنه   
4     عدم التركيز و النسيان        مخ واعصاب   
...                     ...              ...   
1587            تساقط الشعر   جلديه وتناسليه   
1588            هالات سوداء   جلديه وتناسليه   
1589            تساقط الشعر   جلديه وتناسليه   
1590           اكسده البشره   جلديه وتناسليه   
1591         اكزيما العصبيه   جلديه وتناسليه   

                                                    NER  \
0     ﻣﺸﻜﻠﺔ ﻓﻲ ﺍﻟﺮﺟﻠﻴﻦ , ﻣﺸﻜﻠﺔ ﻓﻲ ﺍﻟﻤﺸﻲ , ﻣﺸﻜﻠﺔ ﻓﻲ ﺍ...   
1                                        ﺍﻟﻘﻮﻟﻮﻥ ﺍﻟﻌﺼﺒﻲ   
2                           \n, ﺧﺒﻄﺔ ﺟﺎﻣﺪﺓ\n, ﺩﻡ ﻓﻲ ﺃﻧﻒ   
3      \n, ﺻﺪﺍﻉ ﻣﺘﻘﻄﻊ\n, ﺗﻐﻴﺮ ﻓﻲ ﺿﻐﻂ ﺍﻟﺪﻡ\n, ﻏﺪﺓ ﺣﺪﻳ...   
4     \n, ﺗﺮﻛﻴﺰﻱ ﻣﻨﻌﺪﻡ ﺑﻨﺴﻰ ﺑﺴﺮﻋﻪ ﻭﻣﺒﺮﻛﺰﺵ \n, ﺍﻟﻨﺤﺎﻓ...   
...                                                 ...   
1587                             شعرى وقع من الامام فقط   
1588       كريم خافي للعيوب كونسيلر طبي للهالات السوداء   
1589                                        ﺗﺴﺎﻗﻂ ﺍﻟﺸﻌﺮ   
1590                       ﺗﺄﻛﺴﺪ ﺍلبشرة الدهنية الحساسة   
1591                                    ﺍﻻﻛﺰﻳﻤﺎ ﺍﻟﻌﺼﺒﻴﺔ   

                                             Summarised  \
0     ﺍﻟﻤﺸﻲ ﺑﻨﺴﺒﺎﻟﻲ صعب شوية حتى لو قاعدة او نايمة ر...   
1                                            ﻗﻮﻟﻮﻥ عصبي   
2     ﺧﺒﻄﺔ ﺟﺎﻣﺪﺓ , ﺩﻡ ﻓﻲ ﺃﻧﻒ , ﻣﺶ ﺣﺎﺳﺲ ﺑﺄﺳﻨﺎﻧﻲ , ﻛﺪﻣ...   
3     ﺻﺪﺍﻉ ﻣﺘﻘﻄﻊ , ﺗﻐﻴﺮ ﻓﻲ ﺿﻐﻂ ﺍﻟﺪﻡ من وقت للتانى تغ...   
4                 ﺗﺮﻛﻴﺰ ﻣﻨﻌﺪﻡ ﺑﻨﺴﻰ ﺑﺴﺮﻋﺔ ﻭﻣﺒﺮﻛﺰﺵ 21 سنة   
...                                                 ...   
1587                             شعرى وقع من الامام فقط   
1588  هل يوجد كريم خافي للعيوب كونسيلر طبي للهالات ا...   
1589                                        ﺗﺴﺎﻗﻂ ﺍﻟﺸﻌﺮ   
1590                       ﺗﺄﻛﺴﺪ ﺍلبشرة الدهنية الحساسة   
1591                                    ﺍﻻﻛﺰﻳﻤﺎ ﺍﻟﻌﺼﺒﻴﺔ   

                                                 Refine  \
0     \n\n الشكوى مشكلة في الرجلين\n الأعراض صعوبة ا...   
1     قولون العصبي\nيخوان شو الحل مع القولون العصبي ...   
2     \n\n الشكوى وشي خبطة جامدة\n الأعراض\n   بقالي...   
3     صداع متقطع\n ضغط في الرأس حاله اجهاد دائمه وصد...   
4     \n\n تركيز منعدم بنسى بسرعة ومبركزش\n الشكوى ا...   
...                                                 ...   
1587                                                NaN   
1588                                                NaN   
1589                       \n\n تساقط الشعر بدرجة كبيرة   
1590                                                NaN   
1591                                                NaN   

                                                 Post.1  \
0     السلام عليكم انا بنت 19 سنة  , و رجلي اليمين ب...   
1             يخوان شو الحل مع القولون العصبي مشان الله   
2     لو سمحتوا أنا اتخبط في وشي خبطة جامدة وبقالي ث...   
3     حاله اجهاد دائمه وصداع متقطع من وقت للتانى تغي...   
4     عندي 21 سنه تركيزي منعدم بنسى بسرعه ومبركزش \n...  

In [160]:
df['Type']=df['Type'].astype('category')
df['target']=df['Type'].cat.codes

df.head()

Image type                                               Post Severity  \
0    Unknown  السلام عليكم انا بنت 19 سنة  , و رجلي اليمين ب...      حرج   
1    Unknown          يخوان شو الحل مع القولون العصبي مشان الله  غير حرج   
2    Unknown  لو سمحتوا أنا اتخبط في وشي خبطة جامدة وبقالي ث...      حرج   
3    Unknown  حاله اجهاد دائمه وصداع متقطع من وقت للتانى تغي...  غير حرج   
4    Unknown  عندي 21 سنه تركيزي منعدم بنسى بسرعه ومبركزش \n...  غير حرج   

               Diagnosis             Type  \
0              مخ واعصاب        مخ واعصاب   
1             قولون عصبي            باطنه   
2          كدمه في الوجه  انف واذن وحنجره   
3                    ضغط            باطنه   
4  عدم التركيز و النسيان        مخ واعصاب   

                                                 NER  \
0  ﻣﺸﻜﻠﺔ ﻓﻲ ﺍﻟﺮﺟﻠﻴﻦ , ﻣﺸﻜﻠﺔ ﻓﻲ ﺍﻟﻤﺸﻲ , ﻣﺸﻜﻠﺔ ﻓﻲ ﺍ...   
1                                     ﺍﻟﻘﻮﻟﻮﻥ ﺍﻟﻌﺼﺒﻲ   
2                        \n, ﺧﺒﻄﺔ ﺟﺎﻣﺪﺓ\n, ﺩﻡ ﻓﻲ ﺃﻧﻒ   
3   \n, ﺻﺪﺍﻉ ﻣﺘﻘﻄﻊ\n, ﺗﻐﻴﺮ ﻓﻲ ﺿﻐﻂ ﺍﻟﺪﻡ\n, ﻏﺪﺓ ﺣﺪﻳ...   
4  \n, ﺗﺮﻛﻴﺰﻱ ﻣﻨﻌﺪﻡ ﺑﻨﺴﻰ ﺑﺴﺮﻋﻪ ﻭﻣﺒﺮﻛﺰﺵ \n, ﺍﻟﻨﺤﺎﻓ...   

                                          Summarised  \
0  ﺍﻟﻤﺸﻲ ﺑﻨﺴﺒﺎﻟﻲ صعب شوية حتى لو قاعدة او نايمة ر...   
1                                         ﻗﻮﻟﻮﻥ عصبي   
2  ﺧﺒﻄﺔ ﺟﺎﻣﺪﺓ , ﺩﻡ ﻓﻲ ﺃﻧﻒ , ﻣﺶ ﺣﺎﺳﺲ ﺑﺄﺳﻨﺎﻧﻲ , ﻛﺪﻣ...   
3  ﺻﺪﺍﻉ ﻣﺘﻘﻄﻊ , ﺗﻐﻴﺮ ﻓﻲ ﺿﻐﻂ ﺍﻟﺪﻡ من وقت للتانى تغ...   
4              ﺗﺮﻛﻴﺰ ﻣﻨﻌﺪﻡ ﺑﻨﺴﻰ ﺑﺴﺮﻋﺔ ﻭﻣﺒﺮﻛﺰﺵ 21 سنة   

                                              Refine  \
0  \n\n الشكوى مشكلة في الرجلين\n الأعراض صعوبة ا...   
1  قولون العصبي\nيخوان شو الحل مع القولون العصبي ...   
2  \n\n الشكوى وشي خبطة جامدة\n الأعراض\n   بقالي...   
3  صداع متقطع\n ضغط في الرأس حاله اجهاد دائمه وصد...   
4  \n\n تركيز منعدم بنسى بسرعة ومبركزش\n الشكوى ا...   

                                              Post.1  \
0  السلام عليكم انا بنت 19 سنة  , و رجلي اليمين ب...   
1          يخوان شو الحل مع القولون العصبي مشان الله   
2  لو سمحتوا أنا اتخبط في وشي خبطة جامدة وبقالي ث...   
3  حاله اجهاد دائمه وصداع متقطع من وقت للتانى تغي...   
4  عندي 21 سنه تركيزي منعدم بنسى بسرعه ومبركزش \n...   

                                             Refined  \
0  \n\n الشكوى مشكلة في الرجلين\n الأعراض صعوبة ا...   
1  قولون العصبي\nيخوان شو الحل مع القولون العصبي ...   
2  \n\n الشكوى وشي خبطة جامدة\n الأعراض\n   بقالي...   
3  صداع متقطع\n ضغط في الرأس حاله اجهاد دائمه وصد...   
4  \n\n تركيز منعدم بنسى بسرعة ومبركزش\n الشكوى ا...   

                                            NER_POST  \
0  ﻣﺸﻜﻠﺔ ﻓﻲ ﺍﻟﺮﺟﻠﻴﻦ , ﻣﺸﻜﻠﺔ ﻓﻲ ﺍﻟﻤﺸﻲ , ﻣﺸﻜﻠﺔ ﻓﻲ ﺍ...   
1  ﺍﻟﻘﻮﻟﻮﻥ ﺍﻟﻌﺼﺒﻲ يخوان شو الحل مع القولون العصبي...   
2   \n, ﺧﺒﻄﺔ ﺟﺎﻣﺪﺓ\n, ﺩﻡ ﻓﻲ ﺃﻧﻒ لو سمحتوا أنا اتخ...   
3   \n, ﺻﺪﺍﻉ ﻣﺘﻘﻄﻊ\n, ﺗﻐﻴﺮ ﻓﻲ ﺿﻐﻂ ﺍﻟﺪﻡ\n, ﻏﺪﺓ ﺣﺪﻳ...   
4  \n, ﺗﺮﻛﻴﺰﻱ ﻣﻨﻌﺪﻡ ﺑﻨﺴﻰ ﺑﺴﺮﻋﻪ ﻭﻣﺒﺮﻛﺰﺵ \n, ﺍﻟﻨﺤﺎﻓ...   

                                     Summarised_POST  target  
0  ﺍﻟﻤﺸﻲ ﺑﻨﺴﺒﺎﻟﻲ صعب شوية حتى لو قاعدة او نايمة ر...       5  
1  ﻗﻮﻟﻮﻥ عصبي يخوان شو الحل مع القولون العصبي مشا...       1  
2  ﺧﺒﻄﺔ ﺟﺎﻣﺪﺓ , ﺩﻡ ﻓﻲ ﺃﻧﻒ , ﻣﺶ ﺣﺎﺳﺲ ﺑﺄﺳﻨﺎﻧﻲ , ﻛﺪﻣ...       0  
3  ﺻﺪﺍﻉ ﻣﺘﻘﻄﻊ , ﺗﻐﻴﺮ ﻓﻲ ﺿﻐﻂ ﺍﻟﺪﻡ من وقت للتانى تغ...       1  
4  ﺗﺮﻛﻴﺰ ﻣﻨﻌﺪﻡ ﺑﻨﺴﻰ ﺑﺴﺮﻋﺔ ﻭﻣﺒﺮﻛﺰﺵ 21 سنة عندي 21 ...       5

In [161]:
df['Type'].cat.categories


Index(['انف واذن وحنجره', 'باطنه', 'باطنه اطفال', 'جلديه وتناسليه', 'عظام',
       'مخ واعصاب', 'نساء وتوليد'],
      dtype='object')

In [162]:
category_map = {code: category for code, category in enumerate(df['Type'].cat.categories)}
category_map

{0: 'انف واذن وحنجره',
 1: 'باطنه',
 2: 'باطنه اطفال',
 3: 'جلديه وتناسليه',
 4: 'عظام',
 5: 'مخ واعصاب',
 6: 'نساء وتوليد'}

In [163]:
train_end_point = int(df.shape[0] * 0.6)
val_end_point = int(df.shape[0] * 0.8)
df_train = df.iloc[:train_end_point, :]
df_val = df.iloc[train_end_point:val_end_point, :]
df_test = df.iloc[val_end_point:, :]
print(df_train.shape, df_val.shape, df_test.shape)



(955, 13) (318, 13) (319, 13)


In [164]:
# Drop 'type', 'severity', and 'age' columns along with 'label'
dataset_train = Dataset.from_pandas(df_train.drop(['Type', 'Severity','Diagnosis', 'Image type','Refined','NER','Summarised','Refine','Post.1','NER_POST','Post'], axis=1))
dataset_val = Dataset.from_pandas(df_val.drop(['Type', 'Severity','Diagnosis', 'Image type','Refined','NER','Summarised','Refine','Post.1','NER_POST','Post'], axis=1))
dataset_test = Dataset.from_pandas(df_test.drop(['Type', 'Severity','Diagnosis', 'Image type','Refined','NER','Summarised','Refine','Post.1','NER_POST','Post'], axis=1))


In [165]:
dataset_train_shuffled = dataset_train.shuffle(seed=42)  # Using a seed for reproducibility


In [166]:

# Combine them into a single DatasetDict
dataset = DatasetDict({
    'train': dataset_train_shuffled,
    'val': dataset_val,
    'test': dataset_test
})
dataset

DatasetDict({
    train: Dataset({
        features: ['Summarised_POST', 'target'],
        num_rows: 955
    })
    val: Dataset({
        features: ['Summarised_POST', 'target'],
        num_rows: 318
    })
    test: Dataset({
        features: ['Summarised_POST', 'target'],
        num_rows: 319
    })
})

In [167]:
dataset['train']


Dataset({
    features: ['Summarised_POST', 'target'],
    num_rows: 955
})

In [168]:
print(df_train['Type'].unique())


['مخ واعصاب', 'باطنه', 'انف واذن وحنجره', 'باطنه اطفال', 'عظام', 'نساء وتوليد', 'جلديه وتناسليه']
Categories (7, object): ['انف واذن وحنجره', 'باطنه', 'باطنه اطفال', 'جلديه وتناسليه', 'عظام', 'مخ واعصاب', 'نساء وتوليد']


In [169]:
df_train.target.value_counts(normalize=True)


target
1    0.313089
4    0.184293
5    0.119372
2    0.112042
6    0.110995
0    0.104712
3    0.055497
Name: proportion, dtype: float64

In [170]:

class_weights = (1 / df_train.target.value_counts(normalize=True).sort_index()).tolist()
class_weights = torch.tensor(class_weights)
class_weights = class_weights / class_weights.sum()
print("Class Weights:", class_weights)



Class Weights: tensor([0.1528, 0.0511, 0.1428, 0.2883, 0.0868, 0.1340, 0.1441])


In [171]:
model_name = "aubmindlab/bert-base-arabertv2"

In [172]:

quantization_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type='nf4',
    bnb_4bit_use_double_quant=True,
    bnb_4bit_compute_dtype=torch.bfloat16
)

In [173]:
lora_config = LoraConfig(
    r=16,
    lora_alpha=8,
    target_modules=['query', 'key', 'value', 'dense'],  # Simplified layer names
    lora_dropout=0.05,
    bias='none',
    task_type='SEQ_CLS'
)

In [174]:

model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    quantization_config=quantization_config,
    num_labels=len(category_map)
)
model = prepare_model_for_kbit_training(model)
model = get_peft_model(model, lora_config)
model

`low_cpu_mem_usage` was None, now set to True since model is quantized.
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at aubmindlab/bert-base-arabertv2 and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


PeftModelForSequenceClassification(
  (base_model): LoraModel(
    (model): BertForSequenceClassification(
      (bert): BertModel(
        (embeddings): BertEmbeddings(
          (word_embeddings): Embedding(64000, 768, padding_idx=0)
          (position_embeddings): Embedding(512, 768)
          (token_type_embeddings): Embedding(2, 768)
          (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (dropout): Dropout(p=0.1, inplace=False)
        )
        (encoder): BertEncoder(
          (layer): ModuleList(
            (0-11): 12 x BertLayer(
              (attention): BertAttention(
                (self): BertSelfAttention(
                  (query): lora.Linear4bit(
                    (base_layer): Linear4bit(in_features=768, out_features=768, bias=True)
                    (lora_dropout): ModuleDict(
                      (default): Dropout(p=0.05, inplace=False)
                    )
                    (lora_A): ModuleDict(
                      (de

In [175]:
# Initialize the tokenizer with `add_prefix_space` if necessary for the specific model
tokenizer = AutoTokenizer.from_pretrained(model_name, add_prefix_space=True)

# Assign the `eos_token` to be used as the padding token
if tokenizer.pad_token is None:
    tokenizer.pad_token_id = tokenizer.eos_token_id  # Use eos_token_id for padding
    tokenizer.pad_token = tokenizer.eos_token       # Assign eos_token as pad_token

# Update the model configuration to use the tokenizer's pad_token_id
model.config.pad_token_id = tokenizer.pad_token_id
model.config.use_cache = False  # Prevent caching during training for better compatibility

# Resize model embeddings if a new pad_token was added
if len(tokenizer) != model.config.vocab_size:
    model.resize_token_embeddings(len(tokenizer))


In [176]:
batch_size = 16  # You can adjust this based on your system's memory capacity
text = df_test['Summarised_POST'].tolist()

# Initialize an empty list to store the model outputs
all_outputs = []

# Process the sentences in batches
for i in range(0, len(text), batch_size):
    # Get the batch of sentences
    batch_sentences = text[i:i + batch_size]

    # Tokenize the batch
    inputs = tokenizer(batch_sentences, return_tensors="pt", padding=True, truncation=True, max_length=512)

    # Move tensors to the device where the model is (e.g., GPU or CPU)
    inputs = {k: v.to('cuda' if torch.cuda.is_available() else 'cpu') for k, v in inputs.items()}

    # Perform inference and store the logits
    with torch.no_grad():
        outputs = model(**inputs)
        all_outputs.append(outputs['logits'])

In [177]:

final_outputs = torch.cat(all_outputs, dim=0)
final_outputs


tensor([[ 0.0648, -0.4798,  0.5484,  ..., -0.0709,  0.3115, -0.4181],
        [ 0.0952, -0.3796,  0.5517,  ..., -0.3359,  0.3982, -0.3134],
        [ 0.1822, -0.9460,  0.5382,  ..., -0.3163,  0.1816, -0.2915],
        ...,
        [-0.1488, -0.2779,  0.6285,  ..., -0.3454,  0.2494, -0.3080],
        [ 0.0798, -0.2412,  0.5140,  ..., -0.2371,  0.1483, -0.2614],
        [ 0.1280, -0.5875,  0.7260,  ..., -0.4593,  0.2558, -0.6727]],
       device='cuda:0')

In [178]:
final_outputs.argmax(axis=1)


tensor([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 5, 5, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 5, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 5, 5, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 5, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 5, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 5, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 5, 2, 2, 2, 2, 2, 2, 2, 5, 2, 2, 2, 2, 2, 2, 5,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,

In [179]:

df_test['predictions']=final_outputs.argmax(axis=1).cpu().numpy()
df_test['predictions']

<ipython-input-179-7c1d2547ae19>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test['predictions']=final_outputs.argmax(axis=1).cpu().numpy()


1273    2
1274    2
1275    2
1276    2
1277    2
       ..
1587    2
1588    2
1589    2
1590    2
1591    2
Name: predictions, Length: 319, dtype: int64

In [180]:
def get_performance_metrics(df_test):
  y_test = df_test.target
  y_pred = df_test.predictions

  print("Confusion Matrix:")
  print(confusion_matrix(y_test, y_pred))

  print("\nClassification Report:")
  print(classification_report(y_test, y_pred))

  print("Balanced Accuracy Score:", balanced_accuracy_score(y_test, y_pred))
  print("Accuracy Score:", accuracy_score(y_test, y_pred))

In [181]:
get_performance_metrics(df_test)

Confusion Matrix:
[[  0   0  21   0   0   0   0]
 [  0   0  38   0   0   2   0]
 [  0   0  57   0   0   3   0]
 [  0   0 147   0   0   0   0]
 [  0   0   5   0   0   0   0]
 [  0   0  10   0   0   1   0]
 [  1   0  29   0   0   5   0]]

Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        21
           1       0.00      0.00      0.00        40
           2       0.19      0.95      0.31        60
           3       0.00      0.00      0.00       147
           4       0.00      0.00      0.00         5
           5       0.09      0.09      0.09        11
           6       0.00      0.00      0.00        35

    accuracy                           0.18       319
   macro avg       0.04      0.15      0.06       319
weighted avg       0.04      0.18      0.06       319

Balanced Accuracy Score: 0.1487012987012987
Accuracy Score: 0.18181818181818182


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [182]:
df_test['predictions'].value_counts()


predictions
2    307
5     11
0      1
Name: count, dtype: int64

In [183]:
MAX_LEN = 512

In [184]:
def preprocessing_function(examples):
    return tokenizer(examples['Summarised_POST'], truncation=True, max_length=MAX_LEN)

tokenized_datasets = dataset.map(preprocessing_function, batched=True, remove_columns=['Summarised_POST'])
tokenized_datasets = tokenized_datasets.rename_column("target", "label")
tokenized_datasets.set_format("torch")

Map:   0%|          | 0/955 [00:00<?, ? examples/s]

Map:   0%|          | 0/318 [00:00<?, ? examples/s]

Map:   0%|          | 0/319 [00:00<?, ? examples/s]

In [185]:
collate_fn = DataCollatorWithPadding(tokenizer=tokenizer)

In [186]:
def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    predictions = np.argmax(predictions, axis=1)
    return {'balanced_accuracy' : balanced_accuracy_score(predictions, labels),'accuracy':accuracy_score(predictions,labels)}




In [187]:
class CustomTrainer(Trainer):
    def __init__(self, *args, class_weights=None, **kwargs):
        super().__init__(*args, **kwargs)
        # Ensure class_weights is handled correctly
        if class_weights is not None:
            self.class_weights = torch.tensor(class_weights, dtype=torch.float32).to(self.args.device)
        else:
            self.class_weights = None
        self.epoch_logs = []

    def compute_loss(self, model, inputs, return_outputs=False):
        # Extract labels and convert them to long type for cross_entropy
        labels = inputs.pop("labels").long()

        # Forward pass
        outputs = model(**inputs)

        # Extract logits assuming they are directly outputted by the model
        logits = outputs.get('logits')

        # Compute custom loss with class weights for imbalanced data handling
        if self.class_weights is not None:
            loss = F.cross_entropy(logits, labels, weight=self.class_weights)
        else:
            loss = F.cross_entropy(logits, labels)

        return (loss, outputs) if return_outputs else loss

    def log_metrics(self, metrics, epoch):
        # Custom function to log and save metrics
        print(f"Epoch {epoch}: {metrics}")  # Print metrics
        self.epoch_logs.append(metrics)  # Store the results

    def training_epoch_end(self, outputs):
        # Overriding to log after each epoch
        metrics = self.evaluate()  # Evaluate after each epoch
        self.log_metrics(metrics, epoch=len(self.epoch_logs))  # Log metrics


In [188]:
import wandb
wandb.login(key="72d0e227429bd347553a5563b7396b82cb04a364")


wandb: WARNING Calling wandb.login() after wandb.init() has no effect.


True

In [189]:
training_args = TrainingArguments(
    output_dir='sentiment_classification',
    logging_dir='./logs',
    logging_steps=10,
    evaluation_strategy='epoch',
    save_strategy='epoch',
    load_best_model_at_end=True,
    num_train_epochs=25,
    learning_rate=1e-4,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    weight_decay=0.01
)

In [190]:
trainer = CustomTrainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets['train'],
    eval_dataset=tokenized_datasets['val'],
    tokenizer=tokenizer,
    data_collator=collate_fn,
    compute_metrics=lambda eval_pred: {
        'balanced_accuracy': balanced_accuracy_score(eval_pred[1], np.argmax(eval_pred[0], axis=1)),
        'accuracy': accuracy_score(eval_pred[1], np.argmax(eval_pred[0], axis=1))
    },
    class_weights=class_weights  # Pass the weights tensor
)


<ipython-input-187-f7f84dfa52ac>:6: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  self.class_weights = torch.tensor(class_weights, dtype=torch.float32).to(self.args.device)


In [191]:
train_result = trainer.train()

/usr/local/lib/python3.10/dist-packages/torch/utils/checkpoint.py:460: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(


/usr/local/lib/python3.10/dist-packages/torch/utils/checkpoint.py:460: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torch/utils/checkpoint.py:460: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torch/utils/checkpoint.py:460: UserWarning: torch.

In [38]:
df_train['target'].value_counts(normalize=True)

target
1    0.313089
4    0.184293
5    0.119372
2    0.112042
6    0.110995
0    0.104712
3    0.055497
Name: proportion, dtype: float64

In [39]:
df_test['target'].value_counts(normalize=True)

target
3    0.460815
2    0.188088
1    0.125392
6    0.109718
0    0.065831
5    0.034483
4    0.015674
Name: proportion, dtype: float64

In [192]:
def make_predictions(model, df_test):

    # Convert summaries to a list
    sentences = df_test['Summarised_POST'].tolist()

    # Define the batch size
    batch_size = 16  # You can adjust this based on your system's memory capacity

    # Initialize an empty list to store the model outputs
    all_outputs = []

    # Process the sentences in batches
    for i in range(0, len(sentences), batch_size):
        # Get the batch of sentences
        batch_sentences = sentences[i:i + batch_size]

        # Tokenize the batch
        inputs = tokenizer(batch_sentences, return_tensors="pt", padding=True, truncation=True, max_length=512)

        # Move tensors to the device where the model is (e.g., GPU or CPU)
        inputs = {k: v.to('cuda' if torch.cuda.is_available() else 'cpu') for k, v in inputs.items()}

        # Perform inference and store the logits
        with torch.no_grad():
            outputs = model(**inputs)
            all_outputs.append(outputs['logits'])

    final_outputs = torch.cat(all_outputs, dim=0)

    # Update using .loc to avoid SettingWithCopyWarning
    df_test.loc[:, 'predictions'] = final_outputs.argmax(axis=1).cpu().numpy()

    # Apply category mapping
    df_test.loc[:, 'predictions'] = df_test['predictions'].apply(lambda l: category_map[l])

# Make predictions
make_predictions(model, df_test)

In [193]:
def get_performance_metrics(df_test):
    # Convert both target and predictions back to numeric using category_map
    reverse_category_map = {v: k for k, v in category_map.items()}  # Reverse the category_map to map strings to numbers
    y_test = df_test['target']
    y_pred = df_test['predictions'].apply(lambda x: reverse_category_map[x])

    print("Confusion Matrix:")
    print(confusion_matrix(y_test, y_pred))

    print("\nClassification Report:")
    print(classification_report(y_test, y_pred))

    print("Balanced Accuracy Score:", balanced_accuracy_score(y_test, y_pred))
    print("Accuracy Score:", accuracy_score(y_test, y_pred))

# Run the function again
get_performance_metrics(df_test)

Confusion Matrix:
[[ 12   2   2   0   2   3   0]
 [  7  27   2   0   1   1   2]
 [  4   2  45   4   2   3   0]
 [  8   4  11 111   8   3   2]
 [  0   1   0   1   2   0   1]
 [  0   0   0   2   2   5   2]
 [  2   3   0   1   2   0  27]]

Classification Report:
              precision    recall  f1-score   support

           0       0.36      0.57      0.44        21
           1       0.69      0.68      0.68        40
           2       0.75      0.75      0.75        60
           3       0.93      0.76      0.83       147
           4       0.11      0.40      0.17         5
           5       0.33      0.45      0.38        11
           6       0.79      0.77      0.78        35

    accuracy                           0.72       319
   macro avg       0.57      0.63      0.58       319
weighted avg       0.78      0.72      0.74       319

Balanced Accuracy Score: 0.6253578054598463
Accuracy Score: 0.7178683385579937


In [42]:
import os

# Directory to save the model (inside /kaggle/outputs for persistence)
save_directory = "/kaggle/outputs/arabert-post"

# Create the directory if it does not exist
os.makedirs(save_directory, exist_ok=True)

# Save the model
model.save_pretrained(save_directory)

# Save the tokenizer
tokenizer.save_pretrained(save_directory)

print(f"Model and tokenizer saved successfully to '{save_directory}'")


Model and tokenizer saved successfully to '/kaggle/outputs/arabert-post'


In [43]:
import os

# Directory to save the model (inside /kaggle/outputs for persistence)
save_directory = "/kaggle/working/arabert-post"

# Create the directory if it does not exist
os.makedirs(save_directory, exist_ok=True)

# Save the model
model.save_pretrained(save_directory)

# Save the tokenizer
tokenizer.save_pretrained(save_directory)

print(f"Model and tokenizer saved successfully to '{save_directory}'")


Model and tokenizer saved successfully to '/kaggle/working/arabert-post'


In [44]:
import os

# Directory to save the model (inside /kaggle/outputs for persistence)
save_directory = "arabert-post"

# Create the directory if it does not exist
os.makedirs(save_directory, exist_ok=True)

# Save the model
model.save_pretrained(save_directory)

# Save the tokenizer
tokenizer.save_pretrained(save_directory)

print(f"Model and tokenizer saved successfully to '{save_directory}'")


Model and tokenizer saved successfully to 'arabert-post'


In [48]:
!zip -r arabert_post_model.zip /kaggle/working/arabert-post


  adding: kaggle/working/arabert-post/ (stored 0%)
  adding: kaggle/working/arabert-post/tokenizer.json

/usr/lib/python3.10/pty.py:89: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  pid, fd = os.forkpty()


 (deflated 73%)
  adding: kaggle/working/arabert-post/vocab.txt (deflated 62%)
  adding: kaggle/working/arabert-post/special_tokens_map.json (deflated 80%)
  adding: kaggle/working/arabert-post/README.md (deflated 66%)
  adding: kaggle/working/arabert-post/tokenizer_config.json (deflated 90%)
  adding: kaggle/working/arabert-post/adapter_model.safetensors (deflated 7%)
  adding: kaggle/working/arabert-post/adapter_config.json (deflated 52%)


In [49]:
from IPython.display import FileLink
FileLink(r'arabert_post_model.zip')


/kaggle/working/arabert_post_model.zip

In [194]:
import os

# Directory to save the model (inside /kaggle/outputs for persistence)
save_directory = "/kaggle/working/arabert-summarized"

# Create the directory if it does not exist
os.makedirs(save_directory, exist_ok=True)

# Save the model
model.save_pretrained(save_directory)

# Save the tokenizer
tokenizer.save_pretrained(save_directory)

print(f"Model and tokenizer saved successfully to '{save_directory}'")


Model and tokenizer saved successfully to '/kaggle/working/arabert-summarized'


In [195]:
!zip -r arabert_summarized_model.zip /kaggle/working/arabert-summarized


  adding: kaggle/working/arabert-summarized/ (stored 0%)
  adding: kaggle/working/arabert-summarized/tokenizer.json

/usr/lib/python3.10/pty.py:89: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  pid, fd = os.forkpty()


 (deflated 73%)
  adding: kaggle/working/arabert-summarized/vocab.txt (deflated 62%)
  adding: kaggle/working/arabert-summarized/special_tokens_map.json (deflated 80%)
  adding: kaggle/working/arabert-summarized/README.md (deflated 66%)
  adding: kaggle/working/arabert-summarized/tokenizer_config.json (deflated 90%)
  adding: kaggle/working/arabert-summarized/adapter_model.safetensors (deflated 7%)
  adding: kaggle/working/arabert-summarized/adapter_config.json (deflated 52%)


In [196]:
from IPython.display import FileLink
FileLink(r'arabert_summarized_model.zip')


/kaggle/working/arabert_summarized_model.zip