In [1]:
# Install Pytorch
%pip install "torch==2.2.2" tensorboard

# Install Hugging Face libraries
%pip install  --upgrade "transformers==4.40.0" "datasets==2.18.0" "accelerate==0.29.3" "evaluate==0.4.1" "bitsandbytes==0.43.1" "huggingface_hub==0.22.2" "trl==0.8.6" "peft==0.10.0"



   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 755.5/755.5 MB 2.2 MB/s eta 0:00:000:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 410.6/410.6 MB 4.1 MB/s eta 0:00:000:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.1/14.1 MB 81.1 MB/s eta 0:00:00:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.7/23.7 MB 64.3 MB/s eta 0:00:00:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 823.6/823.6 kB 42.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 731.7/731.7 MB 1.8 MB/s eta 0:00:000:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.6/121.6 MB 1.5 MB/s eta 0:00:000:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.5/56.5 MB 8.3 MB/s eta 0:00:000:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.2/124.2 MB 13.3 MB/s eta 0:00:00:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 196.0/196.0 MB 8.6 MB/s eta 0:00:000:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 166.0/166.0 MB 10.0 MB/s eta 0:00:00:00:0100:01
   ━━

In [2]:
from huggingface_hub import login

login(token="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")


Token has not been saved to git credential helper. Pass `add_to_git_credential=True` if you want to set the git credential as well.
Token is valid (permission: read).
Your token has been saved to /root/.cache/huggingface/token
Login successful


In [3]:
import os
import random
import functools
import csv
import pandas as pd
import numpy as np
import torch
import torch.nn.functional as F
import evaluate
import bitsandbytes as bnb
import accelerate

from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score, confusion_matrix, classification_report, balanced_accuracy_score, accuracy_score

from datasets import Dataset, DatasetDict
from peft import LoraConfig, prepare_model_for_kbit_training, get_peft_model

from transformers import (
    AutoModelForSequenceClassification,
    AutoTokenizer,
    BitsAndBytesConfig,
    TrainingArguments,
    Trainer,
    DataCollatorWithPadding
)

In [4]:
!pip install evaluate


/opt/conda/lib/python3.10/pty.py:89: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  pid, fd = os.forkpty()


In [5]:
!pip install bitsandbytes accelerate


In [6]:
!pip install peft


In [162]:
import pandas as pd

# Load the entire dataset
df = pd.read_excel("/kaggle/input/updateddd/reshaped_output2 (6).xlsx")

# Slice the first 1951 rows
df = df.iloc[:1592]

# Display the DataFrame or its information
df

Image type                                               Post Severity  \
0       Unknown  السلام عليكم انا بنت 19 سنة  , و رجلي اليمين ب...      حرج   
1       Unknown          يخوان شو الحل مع القولون العصبي مشان الله  غير حرج   
2       Unknown  لو سمحتوا أنا اتخبط في وشي خبطة جامدة وبقالي ث...      حرج   
3       Unknown  حاله اجهاد دائمه وصداع متقطع من وقت للتانى تغي...  غير حرج   
4       Unknown  عندي 21 سنه تركيزي منعدم بنسى بسرعه ومبركزش \n...  غير حرج   
...         ...                                                ...      ...   
1587        NaN                    شعرى وقع من الامام فقط اعمل ايه  غير حرج   
1588        NaN  لو سمحت يادكتور هل يوجد كريم خافي للعيوب كونسي...  غير حرج   
1589        NaN  عندي تساقط الشعر بدرجة كبيرة لدرجة احط يدي على...      حرج   
1590        NaN  بشرتي دهنيه حساسه ودايما بتأكسد حتى وانا ف الب...  غير حرج   
1591        NaN                              علاج للاكزيما العصبية      حرج   

                  Diagnosis             Type  \
0                 مخ واعصاب        مخ واعصاب   
1                قولون عصبي            باطنه   
2             كدمه في الوجه  انف واذن وحنجره   
3                       ضغط            باطنه   
4     عدم التركيز و النسيان        مخ واعصاب   
...                     ...              ...   
1587            تساقط الشعر   جلديه وتناسليه   
1588            هالات سوداء   جلديه وتناسليه   
1589            تساقط الشعر   جلديه وتناسليه   
1590           اكسده البشره   جلديه وتناسليه   
1591         اكزيما العصبيه   جلديه وتناسليه   

                                                    NER  \
0     ﻣﺸﻜﻠﺔ ﻓﻲ ﺍﻟﺮﺟﻠﻴﻦ , ﻣﺸﻜﻠﺔ ﻓﻲ ﺍﻟﻤﺸﻲ , ﻣﺸﻜﻠﺔ ﻓﻲ ﺍ...   
1                                        ﺍﻟﻘﻮﻟﻮﻥ ﺍﻟﻌﺼﺒﻲ   
2                           \n, ﺧﺒﻄﺔ ﺟﺎﻣﺪﺓ\n, ﺩﻡ ﻓﻲ ﺃﻧﻒ   
3      \n, ﺻﺪﺍﻉ ﻣﺘﻘﻄﻊ\n, ﺗﻐﻴﺮ ﻓﻲ ﺿﻐﻂ ﺍﻟﺪﻡ\n, ﻏﺪﺓ ﺣﺪﻳ...   
4     \n, ﺗﺮﻛﻴﺰﻱ ﻣﻨﻌﺪﻡ ﺑﻨﺴﻰ ﺑﺴﺮﻋﻪ ﻭﻣﺒﺮﻛﺰﺵ \n, ﺍﻟﻨﺤﺎﻓ...   
...                                                 ...   
1587                             شعرى وقع من الامام فقط   
1588       كريم خافي للعيوب كونسيلر طبي للهالات السوداء   
1589                                        ﺗﺴﺎﻗﻂ ﺍﻟﺸﻌﺮ   
1590                       ﺗﺄﻛﺴﺪ ﺍلبشرة الدهنية الحساسة   
1591                                    ﺍﻻﻛﺰﻳﻤﺎ ﺍﻟﻌﺼﺒﻴﺔ   

                                             Summarised  \
0     ﺍﻟﻤﺸﻲ ﺑﻨﺴﺒﺎﻟﻲ صعب شوية حتى لو قاعدة او نايمة ر...   
1                                            ﻗﻮﻟﻮﻥ عصبي   
2     ﺧﺒﻄﺔ ﺟﺎﻣﺪﺓ , ﺩﻡ ﻓﻲ ﺃﻧﻒ , ﻣﺶ ﺣﺎﺳﺲ ﺑﺄﺳﻨﺎﻧﻲ , ﻛﺪﻣ...   
3     ﺻﺪﺍﻉ ﻣﺘﻘﻄﻊ , ﺗﻐﻴﺮ ﻓﻲ ﺿﻐﻂ ﺍﻟﺪﻡ من وقت للتانى تغ...   
4                 ﺗﺮﻛﻴﺰ ﻣﻨﻌﺪﻡ ﺑﻨﺴﻰ ﺑﺴﺮﻋﺔ ﻭﻣﺒﺮﻛﺰﺵ 21 سنة   
...                                                 ...   
1587                             شعرى وقع من الامام فقط   
1588  هل يوجد كريم خافي للعيوب كونسيلر طبي للهالات ا...   
1589                                        ﺗﺴﺎﻗﻂ ﺍﻟﺸﻌﺮ   
1590                       ﺗﺄﻛﺴﺪ ﺍلبشرة الدهنية الحساسة   
1591                                    ﺍﻻﻛﺰﻳﻤﺎ ﺍﻟﻌﺼﺒﻴﺔ   

                                                 Refine  \
0     \n\n الشكوى مشكلة في الرجلين\n الأعراض صعوبة ا...   
1     قولون العصبي\nيخوان شو الحل مع القولون العصبي ...   
2     \n\n الشكوى وشي خبطة جامدة\n الأعراض\n   بقالي...   
3     صداع متقطع\n ضغط في الرأس حاله اجهاد دائمه وصد...   
4     \n\n تركيز منعدم بنسى بسرعة ومبركزش\n الشكوى ا...   
...                                                 ...   
1587                                                NaN   
1588                                                NaN   
1589                       \n\n تساقط الشعر بدرجة كبيرة   
1590                                                NaN   
1591                                                NaN   

                                                 Post.1  \
0     السلام عليكم انا بنت 19 سنة  , و رجلي اليمين ب...   
1             يخوان شو الحل مع القولون العصبي مشان الله   
2     لو سمحتوا أنا اتخبط في وشي خبطة جامدة وبقالي ث...   
3     حاله اجهاد دائمه وصداع متقطع من وقت للتانى تغي...   
4     عندي 21 سنه تركيزي منعدم بنسى بسرعه ومبركزش \n...  

In [163]:
df['Type'] = df['Type'].astype('category')
df['target'] = df['Type'].cat.codes

df.head()


Image type                                               Post Severity  \
0    Unknown  السلام عليكم انا بنت 19 سنة  , و رجلي اليمين ب...      حرج   
1    Unknown          يخوان شو الحل مع القولون العصبي مشان الله  غير حرج   
2    Unknown  لو سمحتوا أنا اتخبط في وشي خبطة جامدة وبقالي ث...      حرج   
3    Unknown  حاله اجهاد دائمه وصداع متقطع من وقت للتانى تغي...  غير حرج   
4    Unknown  عندي 21 سنه تركيزي منعدم بنسى بسرعه ومبركزش \n...  غير حرج   

               Diagnosis             Type  \
0              مخ واعصاب        مخ واعصاب   
1             قولون عصبي            باطنه   
2          كدمه في الوجه  انف واذن وحنجره   
3                    ضغط            باطنه   
4  عدم التركيز و النسيان        مخ واعصاب   

                                                 NER  \
0  ﻣﺸﻜﻠﺔ ﻓﻲ ﺍﻟﺮﺟﻠﻴﻦ , ﻣﺸﻜﻠﺔ ﻓﻲ ﺍﻟﻤﺸﻲ , ﻣﺸﻜﻠﺔ ﻓﻲ ﺍ...   
1                                     ﺍﻟﻘﻮﻟﻮﻥ ﺍﻟﻌﺼﺒﻲ   
2                        \n, ﺧﺒﻄﺔ ﺟﺎﻣﺪﺓ\n, ﺩﻡ ﻓﻲ ﺃﻧﻒ   
3   \n, ﺻﺪﺍﻉ ﻣﺘﻘﻄﻊ\n, ﺗﻐﻴﺮ ﻓﻲ ﺿﻐﻂ ﺍﻟﺪﻡ\n, ﻏﺪﺓ ﺣﺪﻳ...   
4  \n, ﺗﺮﻛﻴﺰﻱ ﻣﻨﻌﺪﻡ ﺑﻨﺴﻰ ﺑﺴﺮﻋﻪ ﻭﻣﺒﺮﻛﺰﺵ \n, ﺍﻟﻨﺤﺎﻓ...   

                                          Summarised  \
0  ﺍﻟﻤﺸﻲ ﺑﻨﺴﺒﺎﻟﻲ صعب شوية حتى لو قاعدة او نايمة ر...   
1                                         ﻗﻮﻟﻮﻥ عصبي   
2  ﺧﺒﻄﺔ ﺟﺎﻣﺪﺓ , ﺩﻡ ﻓﻲ ﺃﻧﻒ , ﻣﺶ ﺣﺎﺳﺲ ﺑﺄﺳﻨﺎﻧﻲ , ﻛﺪﻣ...   
3  ﺻﺪﺍﻉ ﻣﺘﻘﻄﻊ , ﺗﻐﻴﺮ ﻓﻲ ﺿﻐﻂ ﺍﻟﺪﻡ من وقت للتانى تغ...   
4              ﺗﺮﻛﻴﺰ ﻣﻨﻌﺪﻡ ﺑﻨﺴﻰ ﺑﺴﺮﻋﺔ ﻭﻣﺒﺮﻛﺰﺵ 21 سنة   

                                              Refine  \
0  \n\n الشكوى مشكلة في الرجلين\n الأعراض صعوبة ا...   
1  قولون العصبي\nيخوان شو الحل مع القولون العصبي ...   
2  \n\n الشكوى وشي خبطة جامدة\n الأعراض\n   بقالي...   
3  صداع متقطع\n ضغط في الرأس حاله اجهاد دائمه وصد...   
4  \n\n تركيز منعدم بنسى بسرعة ومبركزش\n الشكوى ا...   

                                              Post.1  \
0  السلام عليكم انا بنت 19 سنة  , و رجلي اليمين ب...   
1          يخوان شو الحل مع القولون العصبي مشان الله   
2  لو سمحتوا أنا اتخبط في وشي خبطة جامدة وبقالي ث...   
3  حاله اجهاد دائمه وصداع متقطع من وقت للتانى تغي...   
4  عندي 21 سنه تركيزي منعدم بنسى بسرعه ومبركزش \n...   

                                             Refined  \
0  \n\n الشكوى مشكلة في الرجلين\n الأعراض صعوبة ا...   
1  قولون العصبي\nيخوان شو الحل مع القولون العصبي ...   
2  \n\n الشكوى وشي خبطة جامدة\n الأعراض\n   بقالي...   
3  صداع متقطع\n ضغط في الرأس حاله اجهاد دائمه وصد...   
4  \n\n تركيز منعدم بنسى بسرعة ومبركزش\n الشكوى ا...   

                                            NER_POST  \
0  ﻣﺸﻜﻠﺔ ﻓﻲ ﺍﻟﺮﺟﻠﻴﻦ , ﻣﺸﻜﻠﺔ ﻓﻲ ﺍﻟﻤﺸﻲ , ﻣﺸﻜﻠﺔ ﻓﻲ ﺍ...   
1  ﺍﻟﻘﻮﻟﻮﻥ ﺍﻟﻌﺼﺒﻲ يخوان شو الحل مع القولون العصبي...   
2   \n, ﺧﺒﻄﺔ ﺟﺎﻣﺪﺓ\n, ﺩﻡ ﻓﻲ ﺃﻧﻒ لو سمحتوا أنا اتخ...   
3   \n, ﺻﺪﺍﻉ ﻣﺘﻘﻄﻊ\n, ﺗﻐﻴﺮ ﻓﻲ ﺿﻐﻂ ﺍﻟﺪﻡ\n, ﻏﺪﺓ ﺣﺪﻳ...   
4  \n, ﺗﺮﻛﻴﺰﻱ ﻣﻨﻌﺪﻡ ﺑﻨﺴﻰ ﺑﺴﺮﻋﻪ ﻭﻣﺒﺮﻛﺰﺵ \n, ﺍﻟﻨﺤﺎﻓ...   

                                     Summarised_POST  target  
0  ﺍﻟﻤﺸﻲ ﺑﻨﺴﺒﺎﻟﻲ صعب شوية حتى لو قاعدة او نايمة ر...       5  
1  ﻗﻮﻟﻮﻥ عصبي يخوان شو الحل مع القولون العصبي مشا...       1  
2  ﺧﺒﻄﺔ ﺟﺎﻣﺪﺓ , ﺩﻡ ﻓﻲ ﺃﻧﻒ , ﻣﺶ ﺣﺎﺳﺲ ﺑﺄﺳﻨﺎﻧﻲ , ﻛﺪﻣ...       0  
3  ﺻﺪﺍﻉ ﻣﺘﻘﻄﻊ , ﺗﻐﻴﺮ ﻓﻲ ﺿﻐﻂ ﺍﻟﺪﻡ من وقت للتانى تغ...       1  
4  ﺗﺮﻛﻴﺰ ﻣﻨﻌﺪﻡ ﺑﻨﺴﻰ ﺑﺴﺮﻋﺔ ﻭﻣﺒﺮﻛﺰﺵ 21 سنة عندي 21 ...       5

In [164]:
df['Type'].cat.categories


Index(['انف واذن وحنجره', 'باطنه', 'باطنه اطفال', 'جلديه وتناسليه', 'عظام',
       'مخ واعصاب', 'نساء وتوليد'],
      dtype='object')

In [165]:
category_map = {code: category for code, category in enumerate(df['Type'].cat.categories)}
category_map

{0: 'انف واذن وحنجره',
 1: 'باطنه',
 2: 'باطنه اطفال',
 3: 'جلديه وتناسليه',
 4: 'عظام',
 5: 'مخ واعصاب',
 6: 'نساء وتوليد'}

In [166]:

train_end_point = int(df.shape[0]*0.6)
val_end_point = int(df.shape[0]*0.8)
df_train = df.iloc[:train_end_point,:]
df_val = df.iloc[train_end_point:val_end_point,:]
df_test = df.iloc[val_end_point:,:]
print(df_train.shape, df_test.shape, df_val.shape)


(955, 13) (319, 13) (318, 13)


In [167]:
# Drop 'type', 'severity', and 'age' columns along with 'label'
dataset_train = Dataset.from_pandas(df_train.drop(['Type', 'Severity','Diagnosis', 'Image type','Post','NER','Summarised','Refine','Post.1','Summarised_POST','NER_POST'], axis=1))
dataset_val = Dataset.from_pandas(df_val.drop(['Type', 'Severity','Diagnosis', 'Image type','Post','NER','Summarised','Refine','Post.1','Summarised_POST','NER_POST'], axis=1))
dataset_test = Dataset.from_pandas(df_test.drop(['Type', 'Severity','Diagnosis', 'Image type','Post','NER','Summarised','Refine','Post.1','Summarised_POST','NER_POST'], axis=1))


In [168]:
dataset_train_shuffled = dataset_train.shuffle(seed=42)  # Using a seed for reproducibility


In [169]:

# Combine them into a single DatasetDict
dataset = DatasetDict({
    'train': dataset_train_shuffled,
    'val': dataset_val,
    'test': dataset_test
})
dataset

DatasetDict({
    train: Dataset({
        features: ['Refined', 'target'],
        num_rows: 955
    })
    val: Dataset({
        features: ['Refined', 'target'],
        num_rows: 318
    })
    test: Dataset({
        features: ['Refined', 'target'],
        num_rows: 319
    })
})

In [170]:
dataset['train']


Dataset({
    features: ['Refined', 'target'],
    num_rows: 955
})

In [171]:
print(df_train['Type'].unique())


['مخ واعصاب', 'باطنه', 'انف واذن وحنجره', 'باطنه اطفال', 'عظام', 'نساء وتوليد', 'جلديه وتناسليه']
Categories (7, object): ['انف واذن وحنجره', 'باطنه', 'باطنه اطفال', 'جلديه وتناسليه', 'عظام', 'مخ واعصاب', 'نساء وتوليد']


In [172]:
df_train.target.value_counts(normalize=True)


target
1    0.313089
4    0.184293
5    0.119372
2    0.112042
6    0.110995
0    0.104712
3    0.055497
Name: proportion, dtype: float64

In [173]:

class_weights=(1/df_train.target.value_counts(normalize=True).sort_index()).tolist()
class_weights=torch.tensor(class_weights)
class_weights=class_weights/class_weights.sum()
class_weights



tensor([0.1528, 0.0511, 0.1428, 0.2883, 0.0868, 0.1340, 0.1441])

In [174]:
model_name = "CAMeL-Lab/bert-base-arabic-camelbert-mix"

In [175]:

quantization_config = BitsAndBytesConfig(
    load_in_4bit=True,  # Enable 4-bit quantization
    bnb_4bit_quant_type='nf4',  # Quantization type
    bnb_4bit_use_double_quant=True,  # Double quantization
    bnb_4bit_compute_dtype=torch.bfloat16  # Compute in bfloat16
)

In [176]:
lora_config = LoraConfig(
    r=16,
    lora_alpha=8,
    target_modules=['query', 'key', 'value', 'dense'],  # Simplified layer names
    lora_dropout=0.05,
    bias='none',
    task_type='SEQ_CLS'
)

In [177]:

model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    quantization_config=quantization_config,
    num_labels=len(category_map)
)
model = prepare_model_for_kbit_training(model)
model = get_peft_model(model, lora_config)
model

`low_cpu_mem_usage` was None, now set to True since model is quantized.
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at CAMeL-Lab/bert-base-arabic-camelbert-mix and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


PeftModelForSequenceClassification(
  (base_model): LoraModel(
    (model): BertForSequenceClassification(
      (bert): BertModel(
        (embeddings): BertEmbeddings(
          (word_embeddings): Embedding(30000, 768, padding_idx=0)
          (position_embeddings): Embedding(512, 768)
          (token_type_embeddings): Embedding(2, 768)
          (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (dropout): Dropout(p=0.1, inplace=False)
        )
        (encoder): BertEncoder(
          (layer): ModuleList(
            (0-11): 12 x BertLayer(
              (attention): BertAttention(
                (self): BertSelfAttention(
                  (query): lora.Linear4bit(
                    (base_layer): Linear4bit(in_features=768, out_features=768, bias=True)
                    (lora_dropout): ModuleDict(
                      (default): Dropout(p=0.05, inplace=False)
                    )
                    (lora_A): ModuleDict(
                      (de

In [27]:
!pip install -U bitsandbytes


/opt/conda/lib/python3.10/pty.py:89: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  pid, fd = os.forkpty()


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.1/69.1 MB 24.9 MB/s eta 0:00:00:00:0100:01
  Attempting uninstall: bitsandbytes
    Found existing installation: bitsandbytes 0.43.1
    Uninstalling bitsandbytes-0.43.1:
      Successfully uninstalled bitsandbytes-0.43.1


In [28]:
!pip uninstall bitsandbytes -y
!pip install bitsandbytes
!pip install -U accelerate
!pip install bitsandbytes transformers accelerate


Found existing installation: bitsandbytes 0.45.0
Uninstalling bitsandbytes-0.45.0:
  Successfully uninstalled bitsandbytes-0.45.0
  Using cached bitsandbytes-0.45.0-py3-none-manylinux_2_24_x86_64.whl.metadata (2.9 kB)
Using cached bitsandbytes-0.45.0-py3-none-manylinux_2_24_x86_64.whl (69.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 336.4/336.4 kB 7.4 MB/s eta 0:00:00ta 0:00:01
  Attempting uninstall: accelerate
    Found existing installation: accelerate 0.29.3
    Uninstalling accelerate-0.29.3:
      Successfully uninstalled accelerate-0.29.3


In [178]:
# Initialize the tokenizer with `add_prefix_space` if necessary for the specific model
tokenizer = AutoTokenizer.from_pretrained(model_name, add_prefix_space=True)

# Assign the `eos_token` to be used as the padding token
if tokenizer.pad_token is None:
    tokenizer.pad_token_id = tokenizer.eos_token_id  # Use eos_token_id for padding
    tokenizer.pad_token = tokenizer.eos_token       # Assign eos_token as pad_token

# Update the model configuration to use the tokenizer's pad_token_id
model.config.pad_token_id = tokenizer.pad_token_id
model.config.use_cache = False  # Prevent caching during training for better compatibility

# Resize model embeddings if a new pad_token was added
if len(tokenizer) != model.config.vocab_size:
    model.resize_token_embeddings(len(tokenizer))


In [179]:
batch_size = 16  # You can adjust this based on your system's memory capacity
text = df_test['Refined'].tolist()

# Initialize an empty list to store the model outputs
all_outputs = []

# Process the sentences in batches
for i in range(0, len(text), batch_size):
    # Get the batch of sentences
    batch_sentences = text[i:i + batch_size]

    # Tokenize the batch
    inputs = tokenizer(batch_sentences, return_tensors="pt", padding=True, truncation=True, max_length=512)

    # Move tensors to the device where the model is (e.g., GPU or CPU)
    inputs = {k: v.to('cuda' if torch.cuda.is_available() else 'cpu') for k, v in inputs.items()}

    # Perform inference and store the logits
    with torch.no_grad():
        outputs = model(**inputs)
        all_outputs.append(outputs['logits'])

In [180]:
final_outputs = torch.cat(all_outputs, dim=0)
final_outputs


tensor([[ 0.1401, -0.4235,  0.3422,  ...,  0.3092,  0.2522,  0.6059],
        [ 0.1254, -0.3449,  0.2271,  ...,  0.3272,  0.4321,  0.4889],
        [-0.1635, -0.2864,  0.2727,  ...,  0.3184,  0.1500,  0.4361],
        ...,
        [-0.2936, -0.3300,  0.2060,  ...,  0.2630,  0.0090,  0.4728],
        [-0.0223, -0.3392,  0.5590,  ...,  0.0579, -0.0338,  0.4139],
        [ 0.5309, -0.4975,  0.2958,  ...,  0.5827, -0.0555,  0.4840]],
       device='cuda:0')

In [181]:
final_outputs.argmax(axis=1)


tensor([6, 3, 6, 6, 6, 6, 6, 3, 6, 3, 2, 3, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 6,
        2, 2, 2, 6, 6, 6, 6, 6, 2, 2, 6, 2, 0, 4, 3, 2, 6, 6, 4, 2, 2, 6, 3, 6,
        6, 2, 5, 4, 2, 6, 6, 6, 6, 2, 6, 6, 2, 6, 6, 2, 3, 5, 6, 6, 2, 2, 3, 6,
        2, 4, 2, 6, 4, 4, 5, 6, 6, 3, 2, 3, 2, 6, 5, 6, 5, 6, 5, 2, 6, 4, 6, 6,
        6, 5, 6, 6, 2, 6, 6, 2, 4, 3, 2, 6, 2, 4, 2, 3, 6, 6, 6, 6, 3, 6, 6, 6,
        2, 6, 2, 2, 2, 6, 6, 6, 6, 2, 6, 6, 6, 5, 4, 2, 6, 6, 6, 3, 6, 2, 2, 3,
        6, 6, 5, 6, 3, 4, 6, 2, 6, 6, 6, 0, 6, 3, 6, 2, 6, 6, 6, 6, 6, 3, 6, 5,
        6, 3, 6, 3, 6, 3, 6, 3, 6, 6, 4, 6, 6, 6, 6, 6, 4, 2, 4, 6, 6, 6, 4, 3,
        6, 3, 6, 3, 6, 6, 3, 4, 6, 6, 6, 6, 4, 4, 4, 4, 6, 6, 4, 6, 6, 3, 6, 4,
        6, 6, 6, 6, 6, 3, 6, 4, 3, 4, 4, 6, 4, 2, 6, 0, 6, 3, 6, 6, 3, 2, 6, 4,
        2, 4, 6, 6, 6, 4, 6, 6, 4, 6, 6, 4, 6, 3, 4, 6, 6, 6, 4, 3, 4, 6, 3, 3,
        3, 4, 3, 6, 6, 4, 4, 4, 6, 6, 6, 6, 3, 3, 6, 3, 6, 6, 3, 4, 6, 4, 4, 6,
        6, 6, 4, 4, 2, 4, 6, 3, 4, 6, 6,

In [182]:
df_test['Type'].value_counts()


Type
جلديه وتناسليه     147
باطنه اطفال         60
باطنه               40
نساء وتوليد         35
انف واذن وحنجره     21
مخ واعصاب           11
عظام                 5
Name: count, dtype: int64

In [183]:
df_test['predictions']=final_outputs.argmax(axis=1).cpu().numpy()
df_test['predictions']

<ipython-input-183-7c1d2547ae19>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test['predictions']=final_outputs.argmax(axis=1).cpu().numpy()


1273    6
1274    3
1275    6
1276    6
1277    6
       ..
1587    6
1588    4
1589    6
1590    2
1591    4
Name: predictions, Length: 319, dtype: int64

In [184]:
def get_performance_metrics(df_test):
  y_test = df_test.target
  y_pred = df_test.predictions

  print("Confusion Matrix:")
  print(confusion_matrix(y_test, y_pred))

  print("\nClassification Report:")
  print(classification_report(y_test, y_pred))

  print("Balanced Accuracy Score:", balanced_accuracy_score(y_test, y_pred))
  print("Accuracy Score:", accuracy_score(y_test, y_pred))

In [185]:
get_performance_metrics(df_test)

Confusion Matrix:
[[ 1  0  6  4  1  0  9]
 [ 1  0 10  3  4  3 19]
 [ 0  0 10  6  4  0 40]
 [ 1  0  5 29 36  1 75]
 [ 0  0  0  0  0  1  4]
 [ 0  0  3  0  1  1  6]
 [ 0  0  9  4  3  6 13]]

Classification Report:
              precision    recall  f1-score   support

           0       0.33      0.05      0.08        21
           1       0.00      0.00      0.00        40
           2       0.23      0.17      0.19        60
           3       0.63      0.20      0.30       147
           4       0.00      0.00      0.00         5
           5       0.08      0.09      0.09        11
           6       0.08      0.37      0.13        35

    accuracy                           0.17       319
   macro avg       0.19      0.12      0.11       319
weighted avg       0.37      0.17      0.20       319

Balanced Accuracy Score: 0.1248431840268575
Accuracy Score: 0.16927899686520376


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [186]:
MAX_LEN = 512
col_to_delete = ['Refined']

def llama_preprocessing_function(examples):
    return tokenizer(examples['Refined'], truncation=True, max_length=MAX_LEN)

tokenized_datasets = dataset.map(llama_preprocessing_function, batched=True, remove_columns=col_to_delete)
tokenized_datasets = tokenized_datasets.rename_column("target", "label")
tokenized_datasets.set_format("torch")

Map:   0%|          | 0/955 [00:00<?, ? examples/s]

Map:   0%|          | 0/318 [00:00<?, ? examples/s]

Map:   0%|          | 0/319 [00:00<?, ? examples/s]

In [187]:
collate_fn = DataCollatorWithPadding(tokenizer=tokenizer)


In [188]:
def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    predictions = np.argmax(predictions, axis=1)
    return {'balanced_accuracy' : balanced_accuracy_score(predictions, labels),'accuracy':accuracy_score(predictions,labels)}




In [189]:
class CustomTrainer(Trainer):
    def __init__(self, *args, class_weights=None, **kwargs):
        super().__init__(*args, **kwargs)
        # Ensure label_weights is a tensor
        if class_weights is not None:
            self.class_weights = torch.tensor(class_weights, dtype=torch.float32).to(self.args.device)
        else:
            self.class_weights = None

        # Initialize an empty list to store epoch results
        self.epoch_logs = []

    def compute_loss(self, model, inputs, return_outputs=False):
        # Extract labels and convert them to long type for cross_entropy
        labels = inputs.pop("labels").long()

        # Forward pass
        outputs = model(**inputs)

        # Extract logits assuming they are directly outputted by the model
        logits = outputs.get('logits')

        # Compute custom loss with class weights for imbalanced data handling
        if self.class_weights is not None:
            loss = F.cross_entropy(logits, labels, weight=self.class_weights)
        else:
            loss = F.cross_entropy(logits, labels)

        return (loss, outputs) if return_outputs else loss

    def log_metrics(self, metrics, epoch):
        # Custom function to log and save metrics
        print(f"Epoch {epoch}: {metrics}")  # Print metrics
        self.epoch_logs.append(metrics)  # Store the results

    def training_epoch_end(self, outputs):
        # Overriding to log after each epoch
        metrics = self.evaluate()  # Evaluate after each epoch
        self.log_metrics(metrics, epoch=len(self.epoch_logs))  # Log metrics

# Setup the trainer with your model and datasets


# Save the logged epoch results to a CSV file
import csv

with open("epoch_results.csv", "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerow(["epoch", "metric_name", "value"])  # Define your columns
    for epoch, metrics in enumerate(trainer.epoch_logs):
        for key, value in metrics.items():
            writer.writerow([epoch + 1, key, value])


In [190]:
import wandb
wandb.login(key="72d0e227429bd347553a5563b7396b82cb04a364")


wandb: WARNING Calling wandb.login() after wandb.init() has no effect.


True

In [191]:
training_args = TrainingArguments(
    output_dir='sentiment_classification',
    logging_dir='./logs',  # Directory to save logs
    logging_steps=10,  # Adjust the frequency of logging steps
    evaluation_strategy='epoch',
    save_strategy='epoch',
    load_best_model_at_end=True,
    num_train_epochs=25,
    learning_rate=1e-4,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    weight_decay=0.01
)


In [192]:

trainer = CustomTrainer(
    model = model,
    args = training_args,
    train_dataset = tokenized_datasets['train'],
    eval_dataset = tokenized_datasets['val'],
    tokenizer = tokenizer,
    data_collator = collate_fn,
    compute_metrics = compute_metrics,
    class_weights=class_weights,
)


<ipython-input-189-c8295c069935>:6: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  self.class_weights = torch.tensor(class_weights, dtype=torch.float32).to(self.args.device)


In [193]:
from accelerate import Accelerator

accelerator = Accelerator()
print(accelerator.state)


Distributed environment: NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cuda

Mixed precision type: no



In [194]:
train_result = trainer.train()


/usr/local/lib/python3.10/dist-packages/torch/utils/checkpoint.py:460: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(


/usr/local/lib/python3.10/dist-packages/torch/utils/checkpoint.py:460: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:2184: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/usr/local/lib/python3.10/dist-packages/torch/utils/checkpoint.py:460: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=F

In [113]:
metrics = trainer.evaluate(eval_dataset=tokenized_datasets['test'])
print("Test Set Metrics:", metrics)

Test Set Metrics: {'eval_loss': 0.8835288286209106, 'eval_balanced_accuracy': 0.6721519570576174, 'eval_accuracy': 0.774294670846395, 'eval_runtime': 7.233, 'eval_samples_per_second': 44.103, 'eval_steps_per_second': 5.53, 'epoch': 25.0}


In [114]:
df_train['target'].value_counts(normalize=True)


target
1    0.313089
4    0.184293
5    0.119372
2    0.112042
6    0.110995
0    0.104712
3    0.055497
Name: proportion, dtype: float64

In [115]:
df_test['target'].value_counts(normalize=True)


target
3    0.460815
2    0.188088
1    0.125392
6    0.109718
0    0.065831
5    0.034483
4    0.015674
Name: proportion, dtype: float64

In [102]:
df_val['target'].value_counts(normalize=True)


target
6    0.330189
5    0.198113
4    0.166667
2    0.163522
0    0.106918
1    0.028302
3    0.006289
Name: proportion, dtype: float64

In [195]:
def make_predictions(model, df_test):

    # Convert summaries to a list
    sentences = df_test['Refined'].tolist()

    # Define the batch size
    batch_size = 16  # You can adjust this based on your system's memory capacity

    # Initialize an empty list to store the model outputs
    all_outputs = []

    # Process the sentences in batches
    for i in range(0, len(sentences), batch_size):
        # Get the batch of sentences
        batch_sentences = sentences[i:i + batch_size]

        # Tokenize the batch
        inputs = tokenizer(batch_sentences, return_tensors="pt", padding=True, truncation=True, max_length=512)

        # Move tensors to the device where the model is (e.g., GPU or CPU)
        inputs = {k: v.to('cuda' if torch.cuda.is_available() else 'cpu') for k, v in inputs.items()}

        # Perform inference and store the logits
        with torch.no_grad():
            outputs = model(**inputs)
            all_outputs.append(outputs['logits'])

    final_outputs = torch.cat(all_outputs, dim=0)

    # Update using .loc to avoid SettingWithCopyWarning
    df_test.loc[:, 'predictions'] = final_outputs.argmax(axis=1).cpu().numpy()

    # Apply category mapping
    df_test.loc[:, 'predictions'] = df_test['predictions'].apply(lambda l: category_map[l])

# Make predictions
make_predictions(model, df_test)


In [196]:
def get_performance_metrics(df_test):
    # Convert both target and predictions back to numeric using category_map
    reverse_category_map = {v: k for k, v in category_map.items()}  # Reverse the category_map to map strings to numbers
    y_test = df_test['target']
    y_pred = df_test['predictions'].apply(lambda x: reverse_category_map[x])

    print("Confusion Matrix:")
    print(confusion_matrix(y_test, y_pred))

    print("\nClassification Report:")
    print(classification_report(y_test, y_pred))

    print("Balanced Accuracy Score:", balanced_accuracy_score(y_test, y_pred))
    print("Accuracy Score:", accuracy_score(y_test, y_pred))

# Run the function again
get_performance_metrics(df_test)


Confusion Matrix:
[[ 16   1   2   0   0   2   0]
 [  3  33   0   1   1   2   0]
 [  3   4  49   0   3   1   0]
 [  2  12  15 109   5   2   2]
 [  0   0   0   0   4   0   1]
 [  0   1   0   0   1   9   0]
 [  0   2   0   2   0   0  31]]

Classification Report:
              precision    recall  f1-score   support

           0       0.67      0.76      0.71        21
           1       0.62      0.82      0.71        40
           2       0.74      0.82      0.78        60
           3       0.97      0.74      0.84       147
           4       0.29      0.80      0.42         5
           5       0.56      0.82      0.67        11
           6       0.91      0.89      0.90        35

    accuracy                           0.79       319
   macro avg       0.68      0.81      0.72       319
weighted avg       0.83      0.79      0.80       319

Balanced Accuracy Score: 0.8069948758724268
Accuracy Score: 0.786833855799373


In [197]:
save_directory = "refined_updated_camelbertbert_type"

# Create the directory if it does not exist
os.makedirs(save_directory, exist_ok=True)

# Save the model
model.save_pretrained(save_directory)

# Save the tokenizer
tokenizer.save_pretrained(save_directory)

print(f"Model and tokenizer saved successfully to '{save_directory}'")

Model and tokenizer saved successfully to 'refined_updated_camelbertbert_type'
